name: Python env

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 black autoflake

      - name: Install simg2img, debugfs, 7z
        run: |
          sudo apt update
          sudo apt install -y android-sdk-libsparse-utils e2fsprogs p7zip-full gh

      - name: Download and reconstruct .img files
        run: |
          mkdir -p images/gta9
          cd images/gta9

          # Download all .part_* files from release
          gh release download --repo sir-solderet/vendor_tree_generator --tag v1.0 -p "*.part_*"

          # Reconstruct all split images like system.img, vendor.img, etc.
          for part in *.part_aa; do
            base=$(basename "$part" .part_aa)
            echo "Reconstructing $base.img"
            cat "$base".part_* > "$base.img"
            rm "$base".part_*
            file "$base.img" || true
            7z l "$base.img" || echo "Warning: 7z listing failed for $base.img"
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run vendor tree generator
        run: |
          python main.py \
            --vendor samsung \
            --device gta9 \
            --images images/gta9 \
            --output vendor/samsung/gta9 \
            --verbose

      - name: Upload generated vendor tree
        uses: actions/upload-artifact@v4
        with:
          name: vendor-tree
          path: vendor/samsung/gta9
