name: Python Lint & Format Check

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint and Format Python Code

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black autoflake

      - name: Run autoflake
        run: |
          autoflake --in-place --remove-unused-variables --remove-all-unused-imports -r vendor_tree_generator/

      - name: Run black
        run: |
          black vendor_tree_generator/

      - name: Run flake8
        run: |
          flake8 vendor_tree_generator/
