name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install simg2img and debugfs
        run: |
          sudo apt update
          sudo apt install -y android-sdk-libsparse-utils e2fsprogs p7zip-full

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Download image parts from release
        run: |
          mkdir -p images/gta9
          cd images/gta9
          gh release download v1.0 -p "system.img.part_*"
          cat system.img.part_* > system.img
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Vendor Tree Generator
        run: |
          python main.py \
            --vendor samsung \
            --device gta9 \
            --images images/gta9 \
            --output vendor/samsung/gta9

      - name: Archive vendor tree output
        run: |
          zip -r vendor_tree_output.zip vendor/samsung/gta9

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: vendor_tree
          path: vendor_tree_output.zip
