name: Python Lint & Format Check

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint and Format Python Code

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black autoflake

      - name: Run autoflake (remove unused imports/variables)
        run: |
          autoflake --in-place --remove-unused-variables --remove-all-unused-imports -r .
        continue-on-error: false

      - name: Run black (code formatter)
        run: |
          black vendor_tree_generator/
        continue-on-error: false

      - name: Run flake8 (style check)
        run: |
          flake8 vendor_tree_generator/ --max-line-length=100
        continue-on-error: false
